### ISSUE TITLE
question - incorporating into build.gradle

### ISSUE THREAD

**Issue by jayceekay** [cdimascio/dotenv-kotlin#37]
what's the best practice for integrating this library as early as possible in a gradle based spring boot app? i was hoping that all gradle tasks (for example db migration tasks) would ingest the .env and use that configuration.

**Comment by cdimascio** [comment]
@jayceekay The following repo contains a spring-mvc project. It uses kotlin, instead of java. I hope it provides for a helpful example.

You can find the repo here
https://github.com/cdimascio/kotlin-spring-mvc-template

Note for this project, the dotenv instance is made available globally (with java it could be public static final)

Files of note... 

Build.gradle
https://github.com/cdimascio/kotlin-spring-mvc-template/blob/master/build.gradle

Dotenv instance inits here
https://github.com/cdimascio/kotlin-spring-mvc-template/blob/master/src/main/kotlin/api/Application.kt

Hope this helps

**Comment by jayceekay** [comment]
thanks for the quick response. I'll check it out tomorrow

**Comment by jayceekay** [comment]
this seems to work when loading the spring app, but since this configuration is happening when the spring app runs would this take effect for other gradle tasks? for example when i run the spring app i can clearly see it's ingesting my `.env` file, but when i run `./gradlew flywayInfo` i see this:
```
$ ./gradlew flywayInfo
> Task :flywayInfo FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayInfo'.
> Error occurred while executing flywayInfo
  Unable to connect to the database. Configure the url, user and password!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more
 log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```

edit: just to clarify, that's why i was hoping to inject it into the `build.gradle` itself, to make dotenv do its thing and create an ENV which is accessible to all the gradle tasks

**Comment by cdimascio** [comment]
What you want to do is certainly doable, however I'm not a gradle expert. 

Nonetheless, perhaps this SO post will help some or at least help you to put you on the right path.

https://stackoverflow.com/q/26314709/2616755

Note that in your case, you need to load the lib from maven Central, rather than use a local jar. You'll  likely need to be sure mavencentral repo is available for the buildscript

**Comment by PericlesTheo** [comment]
I don't know if this is relevant for others but this is how I solved this in my `build.gradle.tks`

```kotlin
import io.github.cdimascio.dotenv.dotenv

val dotenv = dotenv {
    ignoreIfMissing = true
}

// The buildscript was the thing I needed
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("io.github.cdimascio:dotenv-kotlin:6.4.1")
    }
}

dependencies {
    implementation("io.github.cdimascio:dotenv-kotlin:6.4.1")
}
```

With this change, I was able to do read the env vars in `build.gradle.tks`

```koltin
repositories {
    mavenCentral()
    maven(dotenv.get("SOME_MAVEN_URL")) // Random example but now the .env is read
}
```
