### ISSUE TITLE
kotlin libs are required

### ISSUE THREAD

**Issue by martin-jamszolik** [cdimascio/dotenv-kotlin#47]
Hi There,
I was happy to find your project,  However I found that it requires `kotlin` libraries to run.
Trying the following failed.

```<dependency>
            <groupId>io.github.cdimascio</groupId>
            <artifactId>java-dotenv</artifactId>
            <version>5.2.2</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
Is there no way we can compile this project for Java runtime only?
I need to keep my dependencies as light as possible, expected this project to be very small and not requiring any additional libraries.

Thanks.

**Comment by cdimascio** [comment]
@martin-jamszolik i'm working on a pure java version. it's available [here](https://github.com/cdimascio/dotenv-java) and has the same api as the this package. 

note that it's not yet available on jcenter and mavencentral, though it should be there within the next few days.

in the meantime, i posted it to github's maven repo [here](https://github.com/cdimascio/dotenv-java/packages/404788). the  jar from there as well. 

EDIT: the pure java variant is now available on Jcenter, [here](https://bintray.com/cdimascio/maven/dotenv-java/1.0.2)

**Comment by cdimascio** [comment]
@martin-jamszolik i am also planning a new major version of this package that uses the package referenced above as a dep. Ultimately, this package will only contain the Kotlin DSL.

**Comment by cdimascio** [comment]
### The Kotlin enabled version lves in this repo [dotenv-kotlin](https://github.com/cdimascio/dotenv-kotlin)

<p align="left">
	<a href="https://github.com/cdimascio/dotenv-kotlin"><img src="https://raw.githubusercontent.com/cdimascio/dotenv-kotlin/master/assets/kotlin-dotenv-logo.png" alt="dotenv" width="250" /></a>
</p>

### The pure Java version lives at [dotenv-java](https://github.com/cdimascio/dotenv-java)

<p align="left">
	<a href="https://github.com/cdimascio/dotenv-java"><img src="https://raw.githubusercontent.com/cdimascio/dotenv-java/master/assets/dotenv-java-logo.png" alt="dotenv-java" width="260" /></a>
</p>

### Why the changes?

To avoid confusion. 

java-dotenv was implemented in Kotlin. This meant that Java-only users would end up pulling in some Kotlin deps. In order to keep the package size as small as possible for Java-only users, we've rewritten the dotenv core in Java. 

The [dotenv-java](https://github.com/cdimascio/dotenv-java) project contains the pure Java variant. It implements the same API as the original java-dotenv (with the exception of the Kotlin DSL

The [dotenv-kotlin](https://github.com/cdimascio/dotenv-kotlin) project is almost identical to the previous java-dotenv package. The only difference is that its core is provided by [dotenv-java](https://github.com/cdimascio/dotenv-java). It continues to provide functionality similar to before and includes the Kotlin DSL


### Previous Versions of java-dotenv

The last version of java-env is `5.2.2`. It is available on MavenCentral and JCenter
### Maven 
```xml
<dependency>
    <groupId>io.github.cdimascio</groupId>
    <artifactId>java-dotenv</artifactId>
    <version>5.2.2</version>
</dependency>
```

### Gradle

```groovy
compile 'io.github.cdimascio:dotenv-kotlin:5.2.2'
```
